// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1742804593);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1742804593);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1742804593);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1742804510);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 150);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.startup.homepage_override.buildID", "20250216192613");
user_pref("browser.startup.homepage_override.mstone", "135.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[\"jid1-tsgsxbhncspbwq_jetpack-browser-action\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\",\"unified-extensions-button\"]},\"seen\":[\"save-to-pocket-button\",\"jid1-tsgsxbhncspbwq_jetpack-browser-action\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"unified-extensions-area\",\"nav-bar\"],\"currentVersion\":21,\"newElementCount\":2}");
user_pref("distribution.iniFile.exists.appversion", "135.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECJ4EJs884+tuBAgaVm8SQu6Azw==");
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.jid1-TSgSxBhncsPBWQ@jetpack", true);
user_pref("extensions.installedDistroAddon.uBlock0@raymondhill.net", true);
user_pref("extensions.installedDistroAddon.uanaughtylist@raspberrypi.com", true);
user_pref("extensions.lastAppBuildId", "20250216192613");
user_pref("extensions.lastAppVersion", "135.0.1");
user_pref("extensions.lastPlatformVersion", "135.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-TSgSxBhncsPBWQ@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"uBlock0@raymondhill.net\":\"8d8084ed-2b8d-4326-90f2-a5b40503ff30\",\"uanaughtylist@raspberrypi.com\":\"c29218b7-895b-47c1-86ab-7981ce8ed630\",\"formautofill@mozilla.org\":\"f799fa61-41b7-4c8c-a0fe-39e90297895b\",\"pictureinpicture@mozilla.org\":\"5483865b-1ae9-47f4-bdc7-dd1972dd536b\",\"screenshots@mozilla.org\":\"d109893c-a537-4e03-b925-d954d5b67b39\",\"webcompat-reporter@mozilla.org\":\"c378351c-5b7b-40a6-ab53-a811420efc72\",\"webcompat@mozilla.org\":\"dc2e7209-9554-46f4-984a-af29c2c1b434\",\"jid1-TSgSxBhncsPBWQ@jetpack\":\"e5925d9f-e61c-4ef2-b078-54cc635ff661\",\"default-theme@mozilla.org\":\"7b49a0f3-a94c-46c8-94b9-a1a883a47fcf\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECA1uxy1e2UgdBAiHmHqvekr/HA==");
user_pref("toolkit.telemetry.previousBuildID", "20250216192613");
